[package]
name = "example"
version = "0.1.0"
edition = "2024"
publish = false

[dependencies]
fprime_core = { path = "../fprime_core" }

[build-dependencies]
fprime_build = { path = "../fprime_build" }

[lib]
test = false
bench = false

[[bin]]
name = "example"
test = false
bench = false

[[bin]]
name = "no_op"
test = false
bench = false
