[target.wasm32v1-none]
rustflags = [
    "-Ctarget-cpu=mvp",
    "-Ctarget-feature=+mutable-globals",
    # TODO(tumbar) We do not support this in spacewasm yet
    # "-Ctarget-feature=+bulk-memory",
    "-Clink-args=-zstack-size=512",
    "-Clink-arg=--page-size=1",
]

[build]
target = "wasm32v1-none"
